services:
  kyanite_testnet:
    image: ubuntu:24.04
    container_name: kyanite_testnet-ctn
    restart: always
    ports:
      - "8757:8757"  # TCP mainnet port
      - "8758:8758"  # RPC mainnet port
    volumes:
      - ${HOME}/.kyanite:/root/.kyanite:shared
    command:
      - bash
      - -c
      - |
        if [ ! -f /usr/local/bin/kyanited ]; then
          echo "Kyanite Testnet binary not found, setting up environment..."
          apt-get update && \
          apt-get install -y wget curl unzip && \
          rm -rf /var/lib/apt/lists/* && \
          echo $(curl -s https://api.github.com/repos/decenomy/DSW/releases/latest | grep "browser_download_url" | grep -E "Linux(-x64)?\.zip" | cut -d '"' -f 4) > latest_release_url && \
          echo "Latest release URL: $(cat latest_release_url)" && \
          echo $(basename "$(cat latest_release_url)") > latest_filename && \
          echo "Latest filename: $(cat latest_filename)" && \
          wget "$(cat latest_release_url)" && \
          unzip -q "$(cat latest_filename)" && \
          rm "$(cat latest_filename)" && \
          rm latest_filename && \
          rm latest_release_url && \
          mv kyanite* /usr/local/bin;
        else
          echo "Kyanite Testnet binary already installed, skipping setup."
        fi
        kyanited -testnet=1