FROM decenomy/dsw-windows-x64-builder@sha256:c5102edf92fba810de6596cc9593729b79ab00ca8d88656d4613a3cfa1fecf78

# Set up a development tools directory
WORKDIR /home/app

COPY . /home/app

RUN make docker_windows_test

RUN export PATH="/wrapped:$PATH"
